### ISSUE TITLE
Peer to peer feedback

### ISSUE THREAD

**Issue by Mithi-code** [youmari/leaderboard#4]
### Hi @youmari Great work 😃 👍 

- You followed the requirements perfectly.
- HTML Semantic
- Folder structure is good 
- No broken codes 

Cheers, Happy Coding 💯 😄

**Comment by nevisende** [comment]
Yes. You've really done a great project💯✅. However, you can develop more🚀🚀🚀.  For example, your game Id is static:
https://github.com/youmari/leaderboard/blob/eee4b0c524f32ba378202fb52e19d534333aa813/src/js/api.js#L1
You can write an id creator function in api.js  so that different users can create new games for themselves.
Other things your readme actually doesn't look clearly maybe you can separate terminal code and its description by adding a line. 
Good work, Happy coding 🙂🙂🤳

**Comment by youmari** [comment]
thanks for the feedback
